Alertify.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Alertify.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Alertify.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Alertify.MVC/Controllers/MessageLogController.cs
using Alertify.Application.UseCases.MessageLogs.Commands.CreateMessageLog;
using Alertify.Application.UseCases.MessageLogs.Commands.DeleteMessageLog;
using Alertify.Application.UseCases.MessageLogs.Queries.GetAllMessageLogs;
using Alertify.Application.UseCases.MessageLogs.Queries.GetMessageLogById;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alertify.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MessageLogController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateMessageLog()
        {
            return View();
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> CreateMessageLog([FromForm] CreateMessageLogCommand MessageLog)
        {
            await Mediator.Send(MessageLog);

            return RedirectToAction("GetAllMessageLogs");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateMessageLogFromExcel()
        {
            return View();
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllMessageLogs()
        {
            var MessageLogs = await Mediator.Send(new GetAllMessageLogsQuery());

            return View(MessageLogs);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> UpdateMessageLog(int Id)
        {
            var MessageLog = await Mediator.Send(new GetMessageLogByIdQuery(Id));

            return View(MessageLog);
        }

        public async ValueTask<IActionResult> DeleteMessageLog(int Id)
        {
            await Mediator.Send(new DeleteMessageLogCommand(Id));

            return RedirectToAction("GetAllMessageLogs");
        }
    }
}

Alertify.MVC/Controllers/OrganizationClassificationController.cs
using Alertify.Application.UseCases.OrganizationClassifications.Queries.GetAllOrganizationClassifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alertify.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrganizationClassificationController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllOrganizationClassifications()
        {
            var OrganizationClassifications = await Mediator.Send(new GetAllOrganizationClassificationsQuery());

            return View(OrganizationClassifications);
        }
    }
}

Alertify.MVC/Controllers/OrganizationController.cs
using Alertify.Application.UseCases.Districts;
using Alertify.Application.UseCases.Districts.Queries.GetAllDistricts;
using Alertify.Application.UseCases.OrganizationClassifications;
using Alertify.Application.UseCases.OrganizationClassifications.Queries.GetAllOrganizationClassifications;
using Alertify.Application.UseCases.Organizations.Commands.CreateOrganization;
using Alertify.Application.UseCases.Organizations.Commands.DeleteOrganization;
using Alertify.Application.UseCases.Organizations.Commands.UpdateOrganization;
using Alertify.Application.UseCases.Organizations.Queries.GetAllOrganizations;
using Alertify.Application.UseCases.Organizations.Queries.GetOrganizationById;
using Alertify.Application.UseCases.Regions;
using Alertify.Application.UseCases.Regions.Queries.GetAllRegions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alertify.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrganizationController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateOrganization()
        {
            RegionResponse[] regions = await Mediator.Send(new GetAllRegionsQuery());
            ViewData["Regions"] = regions;

            DistrictResponse[] districts = await Mediator.Send(new GetAllDistrictsQuery());
            ViewData["Districts"] = districts;

            OrganizationClassificationResponse[] organizationClassifications = await Mediator.Send(new GetAllOrganizationClassificationsQuery());
            ViewData["OrganizationClassifications"] = organizationClassifications;

            return View();
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> CreateOrganization([FromForm] CreateOrganizationCommand Organization)
        {
            await Mediator.Send(Organization);

            return RedirectToAction("GetAllOrganizations");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateOrganizationFromExcel()
        {
            return View();
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllOrganizations()
        {
            var Organizations = await Mediator.Send(new GetAllOrganizationsQuery());

            return View(Organizations);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> UpdateOrganization(int Id)
        {
            var Organization = await Mediator.Send(new GetOrganizationByIdQuery(Id));

            RegionResponse[] regions = await Mediator.Send(new GetAllRegionsQuery());
            ViewData["Regions"] = regions;

            DistrictResponse[] districts = await Mediator.Send(new GetAllDistrictsQuery());
            ViewData["Districts"] = districts;

            OrganizationClassificationResponse[] organizationClassifications = await Mediator.Send(new GetAllOrganizationClassificationsQuery());
            ViewData["OrganizationClassifications"] = organizationClassifications;

            return View(Organization);
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> UpdateOrganization([FromForm] UpdateOrganizationCommand Organization)
        {
            await Mediator.Send(Organization);

            return RedirectToAction("GetAllOrganizations");
        }

        public async ValueTask<IActionResult> DeleteOrganization(int Id)
        {
            await Mediator.Send(new DeleteOrganizationCommand(Id));

            return RedirectToAction("GetAllOrganizations");
        }
    }
}

Alertify.MVC/Controllers/SmsTemplateController.cs
using Alertify.Application.UseCases.Organizations;
using Alertify.Application.UseCases.Organizations.Queries.GetAllOrganizations;
using Alertify.Application.UseCases.SmsTemplates.Commands.CreateSmsTemplate;
using Alertify.Application.UseCases.SmsTemplates.Commands.DeleteSmsTemplate;
using Alertify.Application.UseCases.SmsTemplates.Commands.UpdateSmsTemplate;
using Alertify.Application.UseCases.SmsTemplates.Queries.GetAllSmsTemplates;
using Alertify.Application.UseCases.SmsTemplates.Queries.GetSmsTemplateById;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Alertify.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SmsTemplateController : ApiBaseController
    {
        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateSmsTemplate()
        {
            OrganizationResponse[] Organizations = await Mediator.Send(new GetAllOrganizationsQuery());
            ViewData["Organizations"] = Organizations;

            return View();
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> CreateSmsTemplate([FromForm] CreateSmsTemplateCommand SmsTemplate)
        {
            await Mediator.Send(SmsTemplate);

            return RedirectToAction("GetAllSmsTemplates");
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> CreateSmsTemplateFromExcel()
        {
            return View();
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> GetAllSmsTemplates()
        {
            var SmsTemplates = await Mediator.Send(new GetAllSmsTemplatesQuery());

            return View(SmsTemplates);
        }

        [HttpGet("[action]")]
        public async ValueTask<IActionResult> UpdateSmsTemplate(int Id)
        {
            var SmsTemplate = await Mediator.Send(new GetSmsTemplateByIdQuery(Id));

            OrganizationResponse[] Organizations = await Mediator.Send(new GetAllOrganizationsQuery());
            ViewData["Organizations"] = Organizations;

            return View(SmsTemplate);
        }

        [HttpPost("[action]")]
        public async ValueTask<IActionResult> UpdateSmsTemplate([FromForm] UpdateSmsTemplateCommand SmsTemplate)
        {
            await Mediator.Send(SmsTemplate);
            return RedirectToAction("GetAllSmsTemplates");
        }

        public async ValueTask<IActionResult> DeleteSmsTemplate(int Id)
        {
            await Mediator.Send(new DeleteSmsTemplateCommand(Id));

            return RedirectToAction("GetAllSmsTemplates");
        }
    }
}

Alertify.MVC/Views/Home/Index.cshtml
@using Alertify.Domain.Entities.Identity;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="display:flex; flex-direction:column; justify-content:center; align-items:center;">

    <div class="d-flex align-items-center justify-content-center" id="main">
        <img src="/5.jpg" class="logoStyle"/>
    </div>

    @if (User.IsInRole("Admin"))
    {
         <div class="button-container">
             <a asp-controller="Organization" asp-action="GetAllOrganizations" class="btn btn-dark custom-btn">
                 Organizations
             </a>
            <a asp-controller="OrganizationClassification" asp-action="GetAllOrganizationClassifications" class="btn btn-dark custom-btn">
                Organization Classifications
            </a>
             <a asp-controller="SmsTemplate" asp-action="GetAllSmsTemplates" class="btn btn-dark custom-btn">
                 SmsTemplates
             </a>
             <a asp-controller="MessageLog" asp-action="GetAllMessageLogsByCompanyId" class="btn btn-dark custom-btn">
                 Statistics
             </a>
         </div>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
    {
        <div class="button-container">
             <a asp-controller="Organization" asp-action="GetAllOrganizations" class="btn btn-dark custom-btn">
                 Organizations
             </a>
            <a asp-controller="OrganizationClassification" asp-action="GetAlOrganizationClassifications" class="btn btn-dark custom-btn">
                OrganizationClassification
             </a>
             <a asp-controller="SmsTemplate" asp-action="GetAllSmsTemplates" class="btn btn-dark custom-btn">
                 SmsTemplates
             </a>
             <a asp-controller="MessageLog" asp-action="GetAllMessageLogs" class="btn btn-dark custom-btn">
                 Statistics
             </a>
         </div>
    }
</div>

<style>
    .button-container {
        margin-top: 20px;
    }

    .custom-btn {
        color: black;
        background-color: white;
    }
</style>

<section id="about" class="section">
    <h2>About Us</h2>
    <p>
        We are a leading SMS service provider dedicated to helping businesses connect with their customers effectively.
        Our platform offers reliable and efficient messaging solutions tailored to meet your specific needs.
    </p>
</section>

<section id="services" class="section">
    <h2>Our Services</h2>
    <ul>
        <li>Bulk SMS Messaging</li>
        <li>Two-Way SMS Communication</li>
        <li>SMS API Integration</li>
        <li>Custom SMS Solutions</li>
    </ul>
</section>

<section id="contact" class="section">
    <h2>Contact Us</h2>
    <p>
        If you have any questions or inquiries, please feel free to contact us.
    </p>
    <p>
        Email: <a href="mailto:info@example.com">info@example.com</a>
    </p>
    <p>
        Phone: +1234567890
    </p>
</section>